### ISSUE TITLE
--skip-root-check throws an error 

### ISSUE THREAD

**Issue by YevgenK** [netz98/n98-magerun#1048]
**Steps to reproduce:**
1. download latest version of n98-magerun.phar (wget https://files.magerun.net/n98-magerun.phar)
2. run `php n98-magerun.phar --skip-root-check`

**Expected result:**
You can see list of available commands

**Actual result:**
Instead you see Fatal error:
```bash
root@88b02164559b:/var/www/outl1# n98-magerun --skip-root-check 
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to N98\Magento\Application\Console\EventSubscriber\CheckRootUser::debugWriteln() must be an instance of N98\Magento\Application\Console\Event, instance of Symfony\Component\Console\Event\ConsoleEvent given, called in phar:///usr/local/bin/n98-magerun/src/N98/Magento/Application/Console/EventSubscriber/CheckRootUser.php on line 51 and defined in phar:///usr/local/bin/n98-magerun/src/N98/Magento/Application/Console/EventSubscriber/CheckRootUser.php:82
Stack trace:
#0 phar:///usr/local/bin/n98-magerun/src/N98/Magento/Application/Console/EventSubscriber/CheckRootUser.php(51): N98\Magento\Application\Console\EventSubscriber\CheckRootUser->debugWriteln(Object(Symfony\Component\Console\Event\ConsoleEvent), 'Skipping root-c...')
#1 phar:///usr/local/bin/n98-magerun/vendor/symfony/event-dispatcher/EventDispatcher.php(264): N98\Magento\Application\Console\EventSubscriber\CheckRootUser->checkRunningAsRootUser(Object(Symfony\Component\Console\Event\ConsoleEvent), 'n98-magerun.app...' in phar:///usr/local/bin/n98-magerun/src/N98/Magento/Application/Console/EventSubscriber/CheckRootUser.php on line 82`
```

Here is version of n98-magerun 
```bash
root@88b02164559b:/var/www/outl1# n98-magerun -v
n98-magerun2 4.0.2 by netz98 GmbH
```

Here is version of PHP
```bash
root@88b02164559b:/var/www/outl1# php -v 
PHP 7.2.24-0ubuntu0.18.04.2 (cli) (built: Jan 13 2020 18:39:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

**Update 21/Jan/2020:**
There is a list of affected versions:
4.0.0
4.0.1
4.0.2

Works fine for version 3.2.0 and bellow. **As a workaround** I'd suggest to revert to this version.

**Comment by cmuench** [comment]
@YevgenK thanks for reporting.
Can you please create the issue in the correct project, again?
https://github.com/netz98/n98-magerun/issues/1048

**Comment by YevgenK** [comment]
thank you for the link, https://github.com/netz98/n98-magerun2/issues/523 is created
