### ISSUE TITLE
sys:setup:incremental causes PHP Fatal error: Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by bluec** [netz98/n98-magerun#888]
I think this has only become apparent in PHP 7.1 with the newly implemented strict argument count. It means sys:setup:incremental won't run on PHP 7.1.x and does highlight an issue that the call to Symfony\Component\Console\Helper\DialogHelper::askAndValidate() is not including the third argument which is required.

```
$ php --version
PHP 7.1.0 (cli) (built: Dec  1 2016 08:13:15) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0, Copyright (c) 1999-2016, by Zend Technologies
```

```
$ magerun --version
n98-magerun version 1.97.27 by netz98 Gmb
```

```
$ magerun sys:setup:incremental


  Analyzing Setup Resource Classes


Found 76 configured setup resource(s)
Found 1 setup resource(s) which need an update
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Console\Helper\DialogHelper::askAndValidate(), 2 passed in phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/System/Setup/IncrementalCommand.php on line 610 and at least 3 expected in phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Helper/DialogHelper.php:347
Stack trace:
#0 phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/System/Setup/IncrementalCommand.php(610): Symfony\Component\Console\Helper\DialogHelper->askAndValidate(Object(Symfony\Component\Console\Output\ConsoleOutput), '<question>Press...')
#1 phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/System/Setup/IncrementalCommand.php(85): N98\Magento\Command\System\Setup\IncrementalCommand->_listDetailedUpdateInformation(Array)
#2 phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Command/Command.php(259): N98\Magento\Command\System\Setup\IncrementalCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput) in phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Helper/DialogHelper.php on line 347
```

**Comment by tkn98** [comment]
This has been reported earlier in #881, please try the development version and let us know if it solves your issue.

**Comment by tkn98** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the self-update command with the --unstable switch.

**Comment by bluec** [comment]
Apologies for the dupe, not sure how I missed that. The development version appears to fix this, many thanks.

**Comment by ktomk** [comment]
No problem at all. Thanks for confirmation of the fix.
